name: Deploy property-frontend

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}     
      - name: Build Docker Image
        run: docker build \
         --build-arg REACT_APP_API_URL=${{ secrets.REACT_APP_API_URL }} 
         --build-arg REACT_APP_API_URL=${{ secrets.REACT_APP_API_URL }}
         -t gauravwadhwa234/property-frontend .
      - name: Publish Image to Docker Hub
        run: docker push gauravwadhwa234/property-frontend:latest 

  deploy:
    needs: build
    runs-on: self-hosted
    
    steps:
      - name: Pull image from Docker Hub
        run: |
              docker pull gauravwadhwa234/property-frontend:latest

      - name: Delete old container
        run: |
          if [ "$( docker ps -aq -f name=gauravwadhwa234-property-frontend-container)" ]; then
             docker rm -f gauravwadhwa234-property-frontend-container
          fi

      

      - name: Run Docker Container
        run: |
           docker run -d -p 3000:80  --name gauravwadhwa234-property-frontend-container gauravwadhwa234/property-frontend
